baseURL: https://reclaim.letsa.net/
languageCode: nl-be
defaultContentLanguage: nl
title: Open Money en LETS
theme:
  - academic
  - kiera
publishDir: docs
params:
  tagline: Informatie over Open Money en LETS
author:
  name: Maarten Vandekeybus
