baseURL: https://reclaim.letsa.net/
languageCode: nl-be
title: LETS reclaim LETS
theme: kiera
publishDir: docs
params:
  tagline: Voor een juiste voorstelling van het LETSysteem
author:
  name: Maarten Vandekeybus
